apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: ml-project
data:
  # FastAPI configuration
  FASTAPI_URL: "http://fastapi-service.ml-project.svc.cluster.local:8000"
  USE_REDIS: "true"
  
  # Database configuration
  DB_HOST: "postgres-service.ml-project.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "ml_db"
  
  # Redis configuration
  REDIS_HOST: "redis-service.ml-project.svc.cluster.local"
  REDIS_PORT: "6379"
